services:
  - type: web
    name: yampilalert-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8693341837:AAF2lK6bGR3uoLz1kfkZt8IjDQIF18YXHN8
      - key: CHANNEL_ID
        value: "@yampilnews"
      - key: ALERT_API_KEY
        value: b3de42c9:736017aa6745a605c155108e221d31a8
      - key: PORT
        value: 10000
